name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
        
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: joaoppcastelo/namecom-ip-updater:${{ github.event.release.tag_name }}
  